Update user-data
Made new changes

diff --git a/user-data b/user-data
--- a/user-data
+++ b/user-data
@@ -28,11 +28,6 @@ ssh_pwauth: true                    # Enable SSH password authentication for def
 # ## Create your own user (overrides default user configuration)
 users:
   - default
-  - name: ftp
-    lock_passwd: false
-    shell: /usr/sbin/nologin                # Set user default shell
-    chpasswd: { expire: false }     # Do not expire password after first login
-    plain_text_passwd: set_your_password_here
 
 #   - name: myuser                    # Create new custom user
 #     gecos: "My Custom User"         # Set user description
@@ -53,8 +48,6 @@ users:
 
 # ## Set the system timezone
 timezone: "Asia/Kuala_Lumpur"           # Timezone value must exist in /usr/share/zoneinfo
-# # Reference(s):
-# # - https://cloudinit.readthedocs.io/en/latest/topics/modules.html#timezone
 
 # ## Configure NTP pools
 ntp:
@@ -64,42 +57,30 @@ ntp:
     - 1.my.pool.ntp.org
     - 2.my.pool.ntp.org
     - 3.my.pool.ntp.org
-# # Reference(s):
-# # - https://cloudinit.readthedocs.io/en/latest/topics/modules.html#ntp
-#apt:
-#  preserve_sources_list: true
 
-#  sources: 
-#    github_cli:
-#      keyid: 23F3D4EA75716059
-#      source: deb [arch=arm64 signed-by=$KEY_FILE] https://cli.github.com/packages stable main
-  
 # # Update package list, upgrade system or install new packages on first boot
 package_update: true                # Update package list
 package_upgrade: true               # Update system package on first-noot
 package_reboot_if_required: true    # Reboot system after installing or upgrading if needed
 packages:                           # Install additional packages
-  - vlc
-  - screen
-  - proftpd
-  - raspi-gpio
-  - cec-utils
-  - fonts-arphic-ukai
+  - vlc                           #Video player
+  - screen                        #Linux terminal session manager
+  - rsync                         #File synchroniser
+  - cec-utils                     #CEC utility to manage tv via HDMI-CEC
+  - fonts-arphic-ukai             #Font to display chinese character on screen
   
 # # Reference(s):
 # # - https://cloudinit.readthedocs.io/en/latest/topics/modules.html#package-update-upgrade-install
 
 # ## Write custom files to disk
 write_files:
-  - path: /opt/raspivideo/videoloop.sh # File path
+  - path: /opt/tv_video/videoloop.sh # File path
     permissions: "0777"             # File permission
     owner: "root:root"              # File ownership
     content: |                      # File content
       #!/bin/bash
-      PASSWORD=set_your_password_here
-      HTTP_PORT=3210
-      LOOP_PATH=/home/ftp
-      VLC_ARG="-I ncurses --extraintf http --loop $LOOP_PATH --http-password $PASSWORD --http-port $HTTP_PORT"
+      LOOP_PATH=/opt/tv_video/videos
+      VLC_ARG="-I ncurses --loop $LOOP_PATH"
       
       startvlc() {
         stopvlc
@@ -136,7 +117,7 @@ write_files:
         screen_start_vlc
       fi
   
-  - path: /opt/raspivideo/tv.sh
+  - path: /opt/tv_video/tv.sh
     permissions: "0777"             
     owner: "root:root"              
     content: |          
@@ -145,99 +126,48 @@ write_files:
       if [ "$(id -u)" -ne 0 ]; then echo "Please run as root." >&2; exit 1; fi
       
       RELAY_GPIO=17
+      GPIO_PATH=/sys/class/gpio/gpio$RELAY_GPIO
+
+      [[ -e $GPIO_PATH ]] || echo $RELAY_GPIO > /sys/class/gpio/export
+      echo out > $GPIO_PATH/direction
       
       if [[ "$1" == "on" ]]; then
-        raspi-gpio set $RELAY_GPIO op dl
+        echo 0 > $GPIO_PATH/value
         echo "on 0" | /usr/bin/cec-client -s -d 1
       elif [[ "$1" == "off" ]]; then
-        raspi-gpio set $RELAY_GPIO op dh
-        echo "off 0" | /usr/bin/cec-client -s -d 1
-      elif [[ "$1" == "off" ]]; then
-        raspi-gpio set $RELAY_GPIO op dh
+        echo 1 > $GPIO_PATH/value
+        if [[ $(cat $GPIO_PATH/value) == "0" ]]; then 
+          echo "The relay can't be turned off, it might be forced to turn on"
+        fi 
         echo "off 0" | /usr/bin/cec-client -s -d 1
       else
         echo "Please specify on or off"
       fi
       
-  - path: /etc/OliveTin/config.yaml
-    content: |
-      listenAddressSingleHTTPFrontend: 0.0.0.0:1337 
-      logLevel: "INFO"
-
-      actions:   
-      - title: Reboot System
-        shell: reboot
-        icon: backup 
-
-      - title: Ping host
-        shell: ping {{ host }} -c {{ count }}
-        icon: ping
-        arguments:
-          - name: host
-            title: host
-            type: ascii_identifier
-            default: example.com
-            description: The host that you want to ping
-
-          - name: count
-            title: Count
-            type: int
-            default: 4
-            description: How many times to do you want to ping?
-
-      - title: Turn on TV
-        shell: /opt/raspivideo/tv.sh on
-        timeout: 10
-        icon: "&#x23FD"
-
-      - title: Turn off TV
-        timeout: 10
-        shell: /opt/raspivideo/tv.sh off
-        icon: "&#x23FE"
-
-      - title: APT Upgrade 
-        shell: apt update --yes && apt upgrade --yes
-        timeout: 360
-        icon: "&#x1F503"
-
-      - title: Full System Upgrade
-        shell: apt update --yes && apt full-upgrade --yes
-        timeout: 600
-        icon: "&#x2965"
-
-      - title: Restart VLC
-        shell: sudo -u pi /opt/raspivideo/videoloop.sh 
-        icon: "&#x21BA"
-
-      - title: Reboot System
-        shell: reboot
-        icon: restart
 
   - path: /etc/cron.d/videoloop
     content: |                      # File content
-      31 06 * * 1-5 pi /opt/raspivideo/videoloop.sh 
-      31 06 * * 1-5 root /opt/raspivideo/tv.sh on
-      59 14 * * 1-5 pi /opt/raspivideo/videoloop.sh stop
-      59 14 * * 1-5 root /opt/raspivideo/tv.sh off
+      31 06 * * 1-5 pi /opt/tv_video/videoloop.sh 
+      31 06 * * 1-5 root /opt/tv_video/tv.sh on
+      59 14 * * 1-5 pi /opt/tv_video/videoloop.sh stop
+      59 14 * * 1-5 root /opt/tv_video/tv.sh off
       
-      01 06 * * 6 pi /opt/raspivideo/videoloop.sh
-      01 06 * * 6 root /opt/raspivideo/tv.sh on
-      59 12 * * 6 pi /opt/raspivideo/videoloop.sh stop
-      59 12 * * 6 root /opt/raspivideo/tv.sh off
+      01 06 * * 6 pi /opt/tv_video/videoloop.sh
+      01 06 * * 6 root /opt/tv_video/tv.sh on
+      59 12 * * 6 pi /opt/tv_video/videoloop.sh stop
+      59 12 * * 6 root /opt/tv_video/tv.sh off
 
-      @reboot pi /opt/raspivideo/videoloop.sh
-      @reboot root /opt/raspivideo/tv.sh on
+      @reboot pi /opt/tv_video/videoloop.sh
+      @reboot root /opt/tv_video/tv.sh on
 
 # # Reference(s):
 # # - https://cloudinit.readthedocs.io/en/latest/topics/modules.html#write-files
 
 # ## Run commands on first boot (runs after all module)
 runcmd:
+    - mkdir -p /opt/tv_video/videos && chmod -R 777 /opt/tv_video/videos
+
 #Fetch latest olivetin from github since it is not added to main repo
-  - wget -O /tmp/olivetin_latest.deb https://github.com/OliveTin/OliveTin/releases/latest/download/OliveTin_linux_arm64.deb && dpkg -i /tmp/olivetin_latest.deb
-  - systemctl enable --now cron proftpd OliveTin
-  - sed -i '/RequireValidShell/c\RequireValidShell off' /etc/proftpd/proftpd.conf
-  - ip a
 #   - echo BerryOS
 # # Reference(s):
 # # - https://cloudinit.readthedocs.io/en/latest/topics/modules.html#runcmd
